# Generated by Django 2.0.3 on 2018-04-19 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_address', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=15)),
                ('provider', models.CharField(choices=[('NZ Best', 'NZ Best Tour Company'), ('NZ First', 'New Zealand First Bus Tours'), ('Little Black Bus', 'Little Black Bus Individual Tours')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('provider', models.CharField(choices=[('NZ Best', 'NZ Best Tour Company'), ('NZ First', 'New Zealand First Bus Tours'), ('Little Black Bus', 'Little Black Bus Individual Tours')], max_length=30)),
                ('description', models.TextField()),
                ('available', models.BooleanField()),
                ('duration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Duration')),
            ],
            options={
                'permissions': (('can_change_availability', 'Set tour as available'),),
            },
        ),
    ]
