# Generated by Django 2.0.3 on 2018-04-19 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='name',
            new_name='tour_name',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='provider',
        ),
        migrations.AddField(
            model_name='agent',
            name='agent_username',
            field=models.CharField(default='Not defined', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Agent'),
        ),
    ]
